### ISSUE TITLE
The sample notebook can not run with spark2.1.1

### ISSUE THREAD

**Issue by phonchi** [databricks/spark-deep-learning#19] opened 2017-06-10 23:21 UTC
Thank, databricks for open source this great library!

I just use `pyspark --packages databricks:spark-deep-learning:0.1.0-spark2.1-s_2.11` methods to integrate the library on our cluster with spark 2.1.1.

However, when I follow the demo notebook in our Jupyter as follows

```
###1
!curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
!tar xzf flower_photos.tgz
!hadoop fs -put flower_photos/dandelion /dataset/
!hadoop fs -put flower_photos/roses  /dataset/
!hadoop fs -put flower_photos/sunflowers  /dataset/
!hadoop fs -put flower_photos/tulips  /dataset/
img_dir = '/dataset/'
from sparkdl import readImages
from pyspark.sql.functions import lit
###2
tulips_df = readImages(img_dir + "/tulips").withColumn("label", lit(1))
daisy_df = readImages(img_dir + "/daisy").withColumn("label", lit(0))
tulips_train, tulips_test = tulips_df.randomSplit([0.6, 0.4])
daisy_train, daisy_test = daisy_df.randomSplit([0.6, 0.4])
train_df = tulips_train.unionAll(daisy_train)
test_df = tulips_test.unionAll(daisy_test)
train_df.count()
# shows 908
### 3
from pyspark.ml.classification import LogisticRegression
from pyspark.ml import Pipeline
from sparkdl import DeepImageFeaturizer 

featurizer = DeepImageFeaturizer(inputCol="image", outputCol="features", modelName="InceptionV3")
lr = LogisticRegression(maxIter=20, regParam=0.05, elasticNetParam=0.3, labelCol="label")
p = Pipeline(stages=[featurizer, lr])
p_model = p.fit(train_df)
```
The following error occurs:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-d506eed5f19f> in <module>()
----> 1 p_model = p.fit(train_df)

/home/wonglab/spark_install/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
     62                 return self.copy(params)._fit(dataset)
     63             else:
---> 64                 return self._fit(dataset)
     65         else:
     66             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

.........

/tmp/spark-cf8e0bcd-a46a-47a7-9c3f-3e803e4ccead/userFiles-37b63d99-e24e-4e65-a6fb-42a16e65b388/databricks_spark-deep-learning-0.1.0-spark2.1-s_2.11.jar/sparkdl/transformers/named_image.py in _buildTFGraphForName(name, featurize)
    226 def _buildTFGraphForName(name, featurize):
    227     if name == "InceptionV3":
--> 228         modelData = _buildInceptionV3Session(featurize)
    229     else:
    230         raise ValueError("%s is not a supported model. Supported models: %s" % name,

/tmp/spark-cf8e0bcd-a46a-47a7-9c3f-3e803e4ccead/userFiles-37b63d99-e24e-4e65-a6fb-42a16e65b388/databricks_spark-deep-learning-0.1.0-spark2.1-s_2.11.jar/sparkdl/transformers/named_image.py in _buildInceptionV3Session(featurize)
    246         preprocessed = inception_v3.preprocess_input(inputImage)
    247         model = InceptionV3(input_tensor=preprocessed, weights="imagenet",
--> 248                             include_top=(not featurize))
    249     return dict(inputTensorName=inputImage.name,
    250                 outputTensorName=model.output.name,

/usr/local/lib/python2.7/dist-packages/keras/applications/inception_v3.pyc in InceptionV3(include_top, weights, input_tensor, input_shape, classes)
    128         channel_axis = 3
    129 
--> 130     x = conv2d_bn(img_input, 32, 3, 3, subsample=(2, 2), border_mode='valid')
    131     x = conv2d_bn(x, 32, 3, 3, border_mode='valid')
    132     x = conv2d_bn(x, 64, 3, 3)

/usr/local/lib/python2.7/dist-packages/keras/applications/inception_v3.pyc in conv2d_bn(x, nb_filter, nb_row, nb_col, border_mode, subsample, name)
     56                       activation='relu',
     57                       border_mode=border_mode,
---> 58                       name=conv_name)(x)
     59     x = BatchNormalization(axis=bn_axis, name=bn_name)(x)
     60     return x

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __call__(self, x, mask)
    544                                      '`layer.build(batch_input_shape)`')
    545             if len(input_shapes) == 1:
--> 546                 self.build(input_shapes[0])
    547             else:
    548                 self.build(input_shapes)

/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.pyc in build(self, input_shape)
    434                                  name='{}_W'.format(self.name),
    435                                  regularizer=self.W_regularizer,
--> 436                                  constraint=self.W_constraint)
    437         if self.bias:
    438             self.b = self.add_weight((self.nb_filter,),

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in add_weight(self, shape, initializer, name, trainable, regularizer, constraint)
    416         """
    417         initializer = initializations.get(initializer)
--> 418         weight = initializer(shape, name=name)
    419         if regularizer is not None:
    420             self.add_loss(regularizer(weight))

/usr/local/lib/python2.7/dist-packages/keras/initializations.pyc in glorot_uniform(shape, name, dim_ordering)
     62 
     63 def glorot_uniform(shape, name=None, dim_ordering='th'):
---> 64     fan_in, fan_out = get_fans(shape, dim_ordering=dim_ordering)
     65     s = np.sqrt(6. / (fan_in + fan_out))
     66     return uniform(shape, s, name=name)

/usr/local/lib/python2.7/dist-packages/keras/initializations.pyc in get_fans(shape, dim_ordering)
     15         if dim_ordering == 'th':
     16             receptive_field_size = np.prod(shape[2:])
---> 17             fan_in = shape[1] * receptive_field_size
     18             fan_out = shape[0] * receptive_field_size
     19         elif dim_ordering == 'tf':

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
````

Any idea? Thanks in advance!!

**Comment by sueann** [comment] 2017-06-12 18:56
Hi @phonchi, thanks for checking out the library! Is your Keras configured to use Theano by any chance? The last error output (line 15) suggests keras backend thinking it's in theano mode:
```
/usr/local/lib/python2.7/dist-packages/keras/initializations.pyc in get_fans(shape, dim_ordering)
     15         if dim_ordering == 'th':
     16             receptive_field_size = np.prod(shape[2:])
---> 17             fan_in = shape[1] * receptive_field_size
     18             fan_out = shape[0] * receptive_field_size
     19         elif dim_ordering == 'tf':
```
cc @phi-dbq

**Comment by phi-dbq** [comment] 2017-06-12 19:25
Hi @phonchi , thank you for checking out the package! 
The issue is likely caused by Keras picking up Theano as backend instead of TensorFlow.
Specifically, the image channel arrangement is different.
Would you like to run the following command and see if it prints `channels_last`? 
`python -c 'from keras import backend as K; print(K.image_data_format())'`

There are a few ways to change the default backend to TensorFlow. 
https://github.com/fchollet/keras/blob/master/docs/templates/backend.md
Hope that it helps.

**Comment by phonchi** [comment] 2017-06-14 04:21
@sueann and @phi-dbq , thanks for your prompt apply! It seems like that I configured to use Theano in my keras setting.

Now the code works!

**Comment by thunterdb** [comment] 2017-06-20 23:20
@phonchi this is great to hear, closing this ticket.

**Closed by thunterdb** 2017-06-20 23:20 UTC
